### ISSUE TITLE
Extremely annoying screeching sound!

### ISSUE THREAD

**Issue by keem85** [irtimmer/moonlight-embedded#344]
I have some issues with a few games. Skyrim and Sonic Racing Transformed is among many of them.. The games starts with a really high pitched screeching sound that never ends.. With Skyrim it's constant non-stop in both menus and games, and with Sonic All Stars Transformed racing, it's only the intro logos and videos.. Same goes for other games that are showing video snippets etc.

This sound is so high that I have to mute the TV. I'm streaming to my RP2 via the latest GFE and Moonlight. This issue has also been present with previous Moonlight versions.. I also get this issue when streaming to my iPhone too.. So it's not a Raspberry issue, but a Moonlight issue.. Please help out or confirm?

Please provide the following info.

**_NVidia Geforce Experience version: 2.10.2.40**
**Moonlight Embedded version:2.1.4**
**Moonlight Embedded running on:** Raspberry Pi 2 B

**Output of Moonlight Embedded: Raspberry Pi 2 B**

**What is the expected result? Screeching sound**

**What happens instead of that? The game starts**

**Comment by alfalfa1978** [comment]
I had the same with AC Syndicate and Dead or Alive 5 (only in the beginning / intros).
In my case the problem is solved by using the option: -surround, although it gives me no real digital surround sound (only 2 channel pcm). But the screeching sound is now gone and Street Fighter V has sound (no sound without -surround option).
