### ISSUE TITLE
Controller aims straight up on games

### ISSUE THREAD

**Issue by TheConsciousness** [irtimmer/moonlight-embedded#438]
Please provide the following info.

**_NVidia Geforce Experience version:_** 3.1.2.31 (latest 11/18/16)
**Moonlight Embedded version:** 2.2.2
**Moonlight Embedded running on:** Raspberry Pi 3

**Output of Moonlight Embedded:** 
Normal output

**What is the expected result?**
Cursor disappears and controller provides the ability to aim in Steam first person shooter games. 

**What happens instead of that?**
Cursor remains in middle of screen and aim always moves straight up. My character looks to the sky.

**Comment by 7hunderbug** [comment]
Are you using a carrot as the controller? If so, are you using the default carrot cake recipe? If you are and the problem still persists you might need more cinnamon otherwise you should try a different recipe; how about carrot salad?

On 19 November 2016 04:45:50 GMT+00:00, TheConsciousness <notifications@github.com> wrote:
>Please provide the following info.
>
>**_NVidia Geforce Experience version:_** 3.1.2.31 (latest 11/18/16)
>**Moonlight Embedded version:** 2.2.2
>**Moonlight Embedded running on:** Raspberry Pi 3
>
>**Output of Moonlight Embedded:** 
>Normal output
>
>**What is the expected result?**
>Cursor disappears and controller provides the ability to aim in Steam
>first person shooter games. 
>
>**What happens instead of that?**
>Cursor remains in middle of screen and aim always moves straight up. My
>character looks to the sky.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/irtimmer/moonlight-embedded/issues/438

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by irtimmer** [comment]
You need to map the controller to fix issues with input
