### ISSUE TITLE
PS3 controller not working

### ISSUE THREAD

**Issue by tijmenvn** [irtimmer/moonlight-embedded#51]
I've got my PS3 controller connected over USB, got it working using jstest /dev/input/js0.
It also works in retropie, but in steam it isn't recognized. when i go to options in steam, and to controller. It seems to recognize an controller. But it doesn't take inputs. I have tried to use the -input /dev/input/js0 parameter. but it doesn't make a difference. I'm also not familiar with mapping files. So I haven't created one.

anyone having luck setting an PS3 controller up and letting it work in steam?

EDIT: This is the error code I get:
Exception in thread "Input - Receiver" java.nio.BufferUnderflowException
        at java.nio.Buffer.nextGetIndex(Buffer.java:506)
        at java.nio.HeapByteBuffer.getShort(HeapByteBuffer.java:310)
        at com.limelight.input.EvdevHandler.parseEvent(Unknown Source)
        at com.limelight.input.EvdevReader.run(Unknown Source)
        at java.lang.Thread.run(Thread.java:744)

**Comment by RoelofBerg** [comment]
Hi,

I made it working. Indeed js0 should not be used but event 0 instead. Here's how I did it:

http://embedded-software-architecture.com/wk/index.php/Limelight_on_a_Raspberry_Pi#Howto:_50.24_Steambox_with_Limelight_on_a_Raspberry_Pi 

But, however, I havent managed to finish the key mapping yet. E.g. the right-joystick-press-down-event isn't recognized. Also very often button-press-events are left unrecognized. I'm working on it.

The link above probably solves the original issue. But the PS3 controller is still not fully working. May I hence re-use/continue this thread to ask for asking how to correctly map the joystick-key-down (z ?) button event for PS3 ? And why the buttons (x,y,a,b) react unreliably (maybe the map automatism catches button-release events or button-pushed-hard events - if such exist - instead of the button-slightly-began-to-be-pressed ones ... - if the controller distinguishes the way of pressing so good)

Mapping file see: https://github.com/RoelofBerg/limelightpisteambox/blob/master/PS3.map 

How can I debug/troubleshoot the mapping ? Has anyone allready finished this for PS3 dual shock ?

Thanks a lot,
Roelof

**Comment by RoelofBerg** [comment]
Ignore my last post. I gave up and bought an xbox controller. Here are my steps as far as I came if someone wants to continue: http://embedded-software-architecture.com/wk/index.php/PS3_controller_for_limelight

**Comment by theharleyquin** [comment]
I've gotten PS3 and PS4 controllers to work. I created a mapping from the command line via:

sudo java -jar limelight.jar map -input /dev/input/event2 controller.map

The mapping only works with event#, not js#. Try a few event#, I had to try event0, event1, and event2. Event2 worked for me.
