### ISSUE TITLE
PS3 Controller Issue

### ISSUE THREAD

**Issue by welly321** [irtimmer/moonlight-embedded#533]
The right and left trigger buttons aren't working correctly. They only work if you are pushing either the left or right analog stick at the same time.

**Comment by Dustee** [comment]
I'll assume you are using retropie.

Are you connecting through Bluetooth? If yes you are probably using sixad.

Sixad has options to map triggers as buttons or analog in /var/lib/sixad/profiles/default
It is the "enable_sbuttons" option.
The analog functionality is broken, see [here](https://github.com/irtimmer/moonlight-embedded/issues/218).
The map as buttons functionality doesn't seem to work in moonlight since SDL2 mappings where adopted.

I believe sixad is abandoned software now, so i don't have any hopes of analog trigger support being fixed. You can check [here](https://retropie.org.uk/forum/topic/11638/dualshock-3-4-testers-needed) to see if you can use Bluetooth without sixad.

If you connect through usb i believe xpad is being used.
Here the possibilities are again two. In Retropie check in /etc/modprobe.d/xpad.conf
If triggers_to_buttons=0 then there is analog trigger support and it works great with moonlight.
If triggers_to_buttons=1 then the issue i mentioned above exists.
Also check [here](https://github.com/irtimmer/moonlight-embedded/issues/528).
